before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/furby
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - replacements:
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build(deps):'