version: '3.7'

services:
  hydra:
    image: oryd/hydra:v1.10.6-sqlite
    environment:
      DSN: memory
      SECRETS_SYSTEM: hydra-secret-system
      STRATEGIES_ACCESS_TOKEN: jwt
    ports:
      - "4444:4444"
      - "4445:4445"
    command: serve all --dangerous-force-http
    restart: on-failure
