apiVersion: apps/v1
kind: Deployment
metadata:
  name: furby-deployment
  labels:
    app: furby
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: furby-config
              mountPath: /etc/furby/config.yaml
              subPath: config.yaml
      volumes:
        - name: furby-config
          configMap:
            name: furby-config