apiVersion: v1
kind: Service
metadata:
  name: {{ include "furby.fullname" . }}
  labels:
    {{- include "furby.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: http
  selector:
    {{- include "furby.selectorLabels" . | nindent 4 }}