---

auth:
    type: "noop"
    user-agents: []

credentials:
    id: "ClientId"
    scopes: []
    secret: "ClientSecret"
    url: "https://oauth.server/oauth2/token"

store:
    interval: 300

server:
    cert: ""
    key: ""
    tls: false
