---
stores:
  - interval: 1
    path: /
    credentials:
      id: integration
      secret: secret
      scopes:
        - scope1
      url: http://localhost:4444/oauth2/token
    auth:
      type: noop